name: only_timetable
description: "A timetable app."
publish_to: "none"
version: 1.0.0-beta.0
repository: https://github.com/nohackjustnoobb/Only-Timetable
license: "MIT"

environment:
  sdk: ^3.8.0

dependencies:
  animated_snack_bar: ^0.4.0
  apple_maps_flutter: ^1.4.0
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.1.1
  google_polyline_algorithm: ^3.1.0
  http: ^1.4.0
  intl: ^0.20.2
  isar:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  latlong2: ^0.9.1
  lucide_icons_flutter: ^3.0.3
  mutex: ^3.1.0
  path_provider: ^2.1.5
  provider: ^6.1.5
  scroll_to_index: ^3.0.1
  split_view: ^3.2.1
  url_launcher: ^6.3.1
  yaml: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  isar_generator:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/

flutter:
  uses-material-design: true
  generate: true
  assets:
    - pubspec.yaml
